[appearance]
font_family = "FiraCode Nerd Font Mono"
font_size = 22
text_color = "white"
bg_color = "black"
padding = 5

[terminal]
cols = 78
rows = 24

[cursor]
blink_interval = 0.5

[prompt]
format = "{time} | @{username} {current_dir} {git_branch}"
time_format = "%H:%M:%S"

